### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by omnigenous** [Banh-Canh/ytui#18]
https://aur.archlinux.org/

Please, consider publishing to Arch User Repositories!

https://aur.archlinux.org/packages/ytui-git is already taken but `ytui` and `ytui-bin` is available.

**Comment by Banh-Canh** [comment]
I'll see how i can automate this

**Comment by Banh-Canh** [comment]
Hello, should be done with ytui-bin
in #36

**Comment by omnigenous** [comment]
@Banh-Canh Thank you!

Installed after running `ytui` and was welcomed with an error:

```
error, couldn't read config file: open /home/user/.config/ytui/config.yaml: no such file or directory
```

I fixed it by running:

```sh
mkdir ~/.config/ytui/config.yaml
ytui
```
