### ISSUE TITLE
[Feature Request] Proxy

### ISSUE THREAD

**Issue by WeAreLiving1984** [Banh-Canh/ytui#40]
Can't use invidious without a proxy all public instances are blocked for me. Unless I host my own invidious instances I can use this app.

Can proxy be added via flag or config option? I specifically need socks5 proxy if that matters.

**Comment by Banh-Canh** [comment]
I'll see what I can do, thanks

**Comment by Banh-Canh** [comment]
ahh i'll take a look, opening it back for now, should have tested more sorry

**Comment by Banh-Canh** [comment]
actually it does work through a proxy, mpv start

**Comment by Banh-Canh** [comment]
> Yeah it starts after several minutes [#40 (comment)](https://github.com/Banh-Canh/ytui/issues/40#issuecomment-2385932641)
> 
> Could be part of this [mpv-player/mpv#3373](https://github.com/mpv-player/mpv/issues/3373) 😔
> 
> Without a proxy YouTube is throttled to the oblivion for me.

can you actually stream youtube video through a invidious instance on your browser ? unfortunately i don't think i can do much here
