### ISSUE TITLE
Export subscriptions from Google account

### ISSUE THREAD

**Issue by omnigenous** [Banh-Canh/ytui#43]
I want to use ytui in local mode. Is there a recommended way to export subscriptions from YouTube/Google? Like userscript in browser (ideally, fastest) or bash (or any language really) script to parse YouTube takeout. I just requested YouTube takeout so can't play around parsing data until I actually get it.

**Comment by Banh-Canh** [comment]
I don't know of any sorry, you could try `ytui show subscribed` but you would need to try to auth with youtube first
