### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by omnigenous** [Banh-Canh/ytui#44]
Sixel and kitty's icat can be used for this.

**Comment by Banh-Canh** [comment]
#19 
i'm planning it but it could take time, since i'm using a lib for the menu i'm unsure how I can render it.

I'll try to edit the upstream lib eventually

mentionned in #4 , i'm closing again, please check the other issues if you wanna discuss :)

**Comment by omnigenous** [comment]
Oh my, it's my second duplicated issue about this... https://github.com/Banh-Canh/ytui/issues/19

sorry.
